/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdx.renameFactu.view;

import com.jdx.renameFactu.controller.FileController;
import com.jdx.renameFactu.controller.FolderController;
import com.jdx.renameFactu.controller.interfaces.IFileController;
import com.jdx.renameFactu.controller.interfaces.IFolderController;
import com.jdx.renameFactu.entitys.FolderEntity;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author EQTIC_PROD_JFH
 */
public class FormView extends javax.swing.JFrame {

    /**
     * Creates new form pruebaform
     */
    private IFolderController folderController = new FolderController();
    private IFileController filecontroller = new FileController();

    public FormView() {
        initComponents();
        //Bloqueamos edición campo de texto con ruta
      //  jTextField1.setEditable(false);
        jTextArea1.setEnabled(false);
        //Configuramos solo puedan seleccionarse directorios
        this.jFileChoose = new JFileChooser();
        jFileChoose.setFileSelectionMode(1);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Renombrado de Facturas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormView Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Directorio:");

        jButton1.setText("Lanzar renombrado");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar Directorio");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Acción al pulsar en el botón
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText("");
        label1.setText("Procesando...");
        String url = jTextField1.getText().trim();
        FolderEntity folder = new FolderEntity(url);

        try {

            //Realizamos las validaciones y operaciones con el directorio
            jTextArea1.append("********************************************"+System.lineSeparator());
            jTextArea1.append("Comienzo de proceso de renombrado"+System.lineSeparator());
            jTextArea1.append("--------------"+System.lineSeparator());
            
            jTextArea1.append("Validamos directorio seleccionado"+System.lineSeparator());
            folderController.validateFolder(folder);
            jTextArea1.append("Validado directorio"+System.lineSeparator());
            jTextArea1.append("--------------"+System.lineSeparator());
            jTextArea1.append("Limpieza de archivos que no se van a procesar"+System.lineSeparator());
            folderController.cleanFiles(folder);
            jTextArea1.append("Limpieza de archivos completada"+System.lineSeparator());
            jTextArea1.append("--------------"+System.lineSeparator());
            jTextArea1.append("Localizamos ficheros a procesar"+System.lineSeparator());
            folder.findFiles();
            jTextArea1.append("Se van a procesar "+folder.getFiles().size()+" ficheros"+System.lineSeparator());
            jTextArea1.append("--------------"+System.lineSeparator());
            jTextArea1.append(System.lineSeparator());
            jTextArea1.append("Comenzamos renombrado"+System.lineSeparator());
            //Una vez verificado el directorio procedemos a las operaciones sobre ficheros
            int cnt =  filecontroller.renameFiles(folder.getFiles(),jTextArea1);
            jTextArea1.append("Renombrado finalizado"+System.lineSeparator());
            jTextArea1.append("********************************************"+System.lineSeparator());
            
            label1.setText("Se han renombrado " + cnt + " ficheros de " + folder.getFiles().size());
        } catch (Exception ex) {
            
            jTextArea1.append(ex.getMessage()+System.lineSeparator());
            
            label1.setForeground(Color.RED);
            label1.setText("No se ha podido procesar correctamente");
            Logger.getLogger(FormView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int a = this.jFileChoose.showDialog(this, "Seleccionar un directorio");
        switch (a) {
            case JFileChooser.APPROVE_OPTION:
                jTextField1.setText(jFileChoose.getSelectedFile().getAbsolutePath());
                break;
            case JFileChooser.CANCEL_OPTION:
                break;
            case JFileChooser.ERROR_OPTION:
                break;
        }
    }//GEN-LAST:event_jButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFileChooser jFileChoose;
}
